# frozen_string_literal: true

require "spec_helper"
require "day7"

RSpec.describe Day7 do
  let(:input) do
    <<~INPUT
      .......S.......
      ...............
      .......^.......
      ...............
      ......^.^......
      ...............
      .....^.^.^.....
      ...............
      ....^.^...^....
      ...............
      ...^.^...^.^...
      ...............
      ..^...^.....^..
      ...............
      .^.^.^.^.^...^.
      ...............
    INPUT
  end

  describe "#part1" do
    it "returns the number of times the beam will be split" do
      expect(subject.part1(input)).to eq(21)
    end
  end
end
